name: Release

on:
  push:
    tags: ["v*"]

permissions:
  attestations: write
  contents: read
  id-token: write

jobs:
  release:
    uses: groovemap-music/automation/.github/workflows/reusable-release.yml@833cb464507678c38ab78bd4718ce697399463e9
    with:
      runner: ubuntu-24.04
      repository-name: python-libraries
      setup-command: just setup
      check-command: just check
      release-command: just release-dry-run
      artifact-path: |
        dist/*.whl
        dist/*.tar.gz
        dist/provenance.json
